### ISSUE TITLE
Feat : add Num

### ISSUE THREAD

**Issue by rvbear** [DEV-TINO/Festino-Main-BE#31]
## Task
- [X] 예약시 고정된 번호 생성
- [X] 주문시 고정된 번호 생성
- [X] 주문시 주문 시간 비교해서 몇일차인지 저장
